title: Cameron McElfresh # your name (or website title) here
logo: "/images/logo_new.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm a Ph.D. candidate in Materials Science & Engineering at <a href="https://www.mse.ucla.edu">UCLA</a>, under the guidance of <a href="http://jmarian.bol.ucla.edu">Dr. Jaime Marian</a>. 
  <br><br>
  <img src="/images/c++_logo.png" height="40" width="40">  <img src="/images/python_logo.jpg" height="40" width="80"> <img src="/images/matlab_logo.jpg" height="40" width="106">
  <br><br>
  <a href="https://www.linkedin.com/in/cameronmcelfresh//">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/pdf/Cameron_McElfresh_Resume.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
