title: Cameron McElfresh # your name (or website title) here
logo: "/images/logo_new.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm a Ph.D. candidate in Materials Science & Engineering at <a href="https://www.mse.ucla.edu">UCLA</a>, under the guidance of <a href="http://jmarian.bol.ucla.edu">Dr. Jaime Marian</a>. 
  <br><br>
  We explore material plasticity by means of computational and experimental methods, with a emphasis on developing novel simulation techniques for extreme environments.
  <br><br><br><br>
  <a href="https://www.linkedin.com/in/cameronmcelfresh//">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
